apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: todomvc-projects
metadata:
  annotations:
    description: Template for creating todomvc projects
  name: todomvc-projects
objects:
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: ${APPLICATION_NAME}-build
    creationTimestam: null
  displayName: "${APPLICATION_NAME} - Build"
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: "${APPLICATION_NAME}-dev"
    creationTimestam: null
  displayName: "${APPLICATION_NAME} - Dev"
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: "${APPLICATION_NAME}-stage"
    creationTimestam: null
  displayName: "${APPLICATION_NAME} - Stage"
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    name: "${APPLICATION_NAME}-prod"
    creationTimestam: null
  displayName: "${APPLICATION_NAME} - Prod"
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: todomvc    
